<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__1</name>
   <tag></tag>
   <elementGuidId>ed65f712-ee07-4974-ad8e-678ecec0e544</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='recaptcha-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#recaptcha-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d120ca57-ed1c-49d2-8841-6823762e3d51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4ca7a1bb-3d26-405a-8775-9a762708da5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-12 ml-0 font-weight-regular primary--text v-btn v-btn--has-bg v-btn--rounded theme--dark v-size--large white</value>
      <webElementGuid>e545cd44-7ba3-4710-ad20-7d43acbdea52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>recaptcha-container</value>
      <webElementGuid>794e7ec8-476b-4774-bb49-320ef915b681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Получить код
          </value>
      <webElementGuid>059b806f-1880-4592-9afe-b9905c469de0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recaptcha-container&quot;)</value>
      <webElementGuid>84558077-7caf-4289-8c28-92362f4393f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='recaptcha-container']</value>
      <webElementGuid>fd9ac0b5-ddd0-45cc-b5e5-4642ab3b1549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/div[2]/form/div/button</value>
      <webElementGuid>effe8aa7-90b6-4e73-a532-7a842a15a449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Телефон'])[1]/following::button[1]</value>
      <webElementGuid>b08321af-7982-4056-bde1-b345bb723615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/following::button[1]</value>
      <webElementGuid>1ff06cb8-b86b-4c45-b34a-540ff4065b39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[2]/preceding::button[1]</value>
      <webElementGuid>98b68521-77cf-43f9-80b1-b69639373d50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/button</value>
      <webElementGuid>9841c0e3-75fc-49e7-bce8-5efdf2d1b08f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'recaptcha-container' and (text() = '
            Получить код
          ' or . = '
            Получить код
          ')]</value>
      <webElementGuid>0ff00d29-1d45-436d-947b-97a11558ec5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
