<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__1_2</name>
   <tag></tag>
   <elementGuidId>885b7da2-9325-4ef0-8737-2671c72ce8e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.px-12.ml-0.font-weight-light.v-btn.v-btn--has-bg.v-btn--rounded.theme--dark.v-size--large.primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7714047c-86bf-45ea-a965-71465f0002f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>659ee87f-4053-4cb2-ac58-bd3d18b29952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-12 ml-0 font-weight-light v-btn v-btn--has-bg v-btn--rounded theme--dark v-size--large primary</value>
      <webElementGuid>b40a0db8-70f1-45e1-abb2-074d562e1e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Войти
          </value>
      <webElementGuid>e0e4eef0-9ee1-439b-90fc-2a6e4dd89cc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/main[@class=&quot;v-main&quot;]/div[@class=&quot;v-main__wrap&quot;]/div[@class=&quot;container container--fluid fill-height&quot;]/div[@class=&quot;layout justify-center fill-height wrap&quot;]/div[@class=&quot;login-form my-auto px-4 v-card v-card--flat v-sheet theme--light transparent&quot;]/div[@class=&quot;v-card__text&quot;]/form[@class=&quot;v-form&quot;]/div[@class=&quot;layout column&quot;]/button[@class=&quot;px-12 ml-0 font-weight-light v-btn v-btn--has-bg v-btn--rounded theme--dark v-size--large primary&quot;]</value>
      <webElementGuid>e4a7d0c8-6626-4b80-ab49-f34b2600a5d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[5]</value>
      <webElementGuid>430a18b9-b278-45bf-a983-643582de44f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/div[2]/form[2]/div/button</value>
      <webElementGuid>287dbf38-1c41-4803-82c7-b6e164132d56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Код из смс'])[1]/following::button[2]</value>
      <webElementGuid>a4736736-42c5-4f7b-b6fa-60cf7e0d1132</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[2]/following::button[2]</value>
      <webElementGuid>3f9e7d94-46ab-4b1c-8ba3-84f5b37a2396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Выслать повторно'])[1]/preceding::button[1]</value>
      <webElementGuid>127f6993-df16-4b61-bdf1-7b9b7329ef85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[2]/div/button</value>
      <webElementGuid>d6bfb250-ad12-48d7-9a49-ea86b005a3b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
            Войти
          ' or . = '
            Войти
          ')]</value>
      <webElementGuid>50ec4e82-0b96-46d5-95bf-8bd42cbfa9e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
