<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>ef70bede-9ebf-41e8-bf70-454976b23361</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.px-12.ml-0.mb-8.w-100.font-weight-regular.v-btn.v-btn--outlined.v-btn--rounded.theme--light.v-size--x-large.white--text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>373cf37d-46d6-4818-bb41-913cfc389c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2ae0db13-b6ee-44e6-8b41-5a5cc1df596b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-12 ml-0 mb-8 w-100 font-weight-regular v-btn v-btn--outlined v-btn--rounded theme--light v-size--x-large white--text</value>
      <webElementGuid>edf2d2e6-25c7-4b04-bc28-2e36af32cfe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          Войти
        </value>
      <webElementGuid>63a6dea0-1fff-4f23-9105-da0abd1816e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/main[@class=&quot;v-main&quot;]/div[@class=&quot;v-main__wrap&quot;]/div[@class=&quot;container container--fluid fill-height&quot;]/div[@class=&quot;layout justify-center fill-height wrap&quot;]/div[@class=&quot;my-auto px-4 mb-12 py-0 mb-0 v-card v-card--flat v-sheet theme--light transparent&quot;]/div[@class=&quot;v-card__actions pt-12 px-5&quot;]/div[@class=&quot;row no-gutters&quot;]/div[@class=&quot;col col-12&quot;]/button[@class=&quot;px-12 ml-0 mb-8 w-100 font-weight-regular v-btn v-btn--outlined v-btn--rounded theme--light v-size--x-large white--text&quot;]</value>
      <webElementGuid>48f89c06-0289-4ffa-89cf-131134b93e4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>92f3079f-522a-4f19-b61f-353651637518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div[3]/div/div[2]/button</value>
      <webElementGuid>96a5d51c-d677-467a-8e6d-6421a24f3515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Регистрация'])[1]/following::button[1]</value>
      <webElementGuid>c34028ee-521d-43b0-9f3d-24fb4d328c89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RU'])[1]/preceding::button[1]</value>
      <webElementGuid>815181ea-643a-4cb1-a1c2-c8c2febb6681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>3e27eb17-2739-4df8-b1a7-83fda37b4fd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
          Войти
        ' or . = '
          Войти
        ')]</value>
      <webElementGuid>81a4746a-a729-4970-b669-fcb89717e8e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
