<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__1_2_3</name>
   <tag></tag>
   <elementGuidId>93fe1e8b-f56c-4705-91a3-bcf16943ca9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ma-0.v-btn.v-btn--is-elevated.v-btn--has-bg.v-btn--tile.theme--light.v-size--default</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>08ad9ba0-1437-481a-95f2-e84eaa395590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>518ef072-0923-473e-b831-f850fc83552c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ma-0 v-btn v-btn--is-elevated v-btn--has-bg v-btn--tile theme--light v-size--default</value>
      <webElementGuid>285a9101-e197-4f3d-8781-a61b56ec31be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        Нет
      </value>
      <webElementGuid>5b95df8b-e81d-4a2d-9cf3-653e938a4dd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-dialog__content v-dialog__content--active&quot;]/div[@class=&quot;v-dialog v-dialog--active&quot;]/div[@class=&quot;grey--text text-center pt-7 v-card v-sheet theme--light&quot;]/div[@class=&quot;v-card__actions pa-0 mt-6 d-flex w-100 justify-space-between&quot;]/button[@class=&quot;ma-0 v-btn v-btn--is-elevated v-btn--has-bg v-btn--tile theme--light v-size--default&quot;]</value>
      <webElementGuid>e6ab19b9-9f97-47c0-94ba-862268951d2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>168eaecc-2a14-4c1c-b2ab-1d9e4f89f967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[3]/div/div/div[2]/button</value>
      <webElementGuid>7c2ad816-48ac-4363-a60d-c6c215e466f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Хотите использовать пин-код для входа?'])[1]/following::button[1]</value>
      <webElementGuid>ca477b65-942b-4c82-8598-a42c15e7d1f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ошибка!'])[1]/following::button[2]</value>
      <webElementGuid>7c2bb6ac-9935-4f0a-93a0-dc639e8926d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Да'])[1]/preceding::button[1]</value>
      <webElementGuid>f1100692-0af8-4b95-b34f-659f631b5139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/button</value>
      <webElementGuid>16b8857b-0c28-40ef-a4f4-8a3a298afd85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
        Нет
      ' or . = '
        Нет
      ')]</value>
      <webElementGuid>8cff9d19-5d02-4554-94c0-7c6e93b39b75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
