<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-42</name>
   <tag></tag>
   <elementGuidId>f9ac54d3-376b-44c8-856f-b8ad41017467</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-42']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-42</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6e276f3b-e8a0-4932-9ff2-fb93d3f660cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-42</value>
      <webElementGuid>d0d6fa04-c674-446c-8197-c9f12e6b7da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>aed74b85-93cb-4f82-81e4-7d5e6eb41dd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-42&quot;)</value>
      <webElementGuid>bf2ae84e-af1d-4c65-aeba-8b3283d73b99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-42']</value>
      <webElementGuid>70db11d9-a8ef-4ff3-bcc1-2534e0443aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/div[2]/form[2]/div/div/div/div/div/input</value>
      <webElementGuid>70d6d7c9-8be3-495a-82b0-19990241962a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[2]/div/div/div/div/div/input</value>
      <webElementGuid>46dc18f4-caf4-424f-9622-06077c0fb5f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-42' and @type = 'tel']</value>
      <webElementGuid>18cb0971-22ab-40e4-b352-53b0ce30e3de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
